import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Providers from '@/components/Providers'
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ChatPDF',
  description: 'Generated by create next app',
}
//The root layout is a server component. If you plan to use the <ClerkProvider /> outside the root layout, it will need to be a server component as well.

//to decide which pages are public and which need to hide behind authentication. We do this by creating a middleware.ts file at the root folder (or inside src/ if that is how you set up your app).

//the provider used here is for the react query so that the app dosent have to query again and again to the backend for data and can cache the data for the first call and then use it instead
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <Providers>
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Toaster/>
    </html>
    
    </Providers>
    </ClerkProvider>
  )
}
